### ISSUE TITLE
2.6 - Parsing Expressions

### ISSUE THREAD

**Issue by jolisper** [jolisper/monkey#10]
- [X] Preparing the AST (done by #12) 
- [X] Implementing the Pratt Parser (done by #13) 
- [X] Identifiers (done by #14)
- [X] Integer Literals (done by #15)
- [x] Prefix Operators
- [ ] Infix Operators
